Traceback (most recent call last):
  File "/home/christian/Bin/inactiveOpacityException.py", line 110, in <module>
    ipc.main()
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 514, in main
    raise loop_exception
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 497, in main
    while not self._event_socket_poll():
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 430, in _event_socket_poll
    data, msg_type = self._ipc_recv(self._sub_socket)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 129, in _ipc_recv
    data = sock.recv(14)
           ^^^^^^^^^^^^^
  File "/home/christian/Bin/inactiveOpacityException.py", line 108, in <lambda>
    signal.signal(sig, lambda signal, frame: remove_opacity(ipc))
                                             ^^^^^^^^^^^^^^^^^^^
  File "/home/christian/Bin/inactiveOpacityException.py", line 48, in remove_opacity
    for workspace in ipc.get_tree().workspaces():
                     ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 282, in get_tree
    data = self._message(MessageType.GET_TREE, '')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 166, in _message
    raise e
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 163, in _message
    return self._ipc_send(self._cmd_socket, message_type, payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 146, in _ipc_send
    data, msg_type = self._ipc_recv(sock)
                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 129, in _ipc_recv
    data = sock.recv(14)
           ^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
cannot access local variable 'prev_focused_workspace' where it is not associated with a value
Traceback (most recent call last):
  File "/home/christian/Bin/inactiveOpacityExceptionCorrected.py", line 90, in <module>
    ipc.main()
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 514, in main
    raise loop_exception
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 497, in main
    while not self._event_socket_poll():
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 477, in _event_socket_poll
    raise e
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 474, in _event_socket_poll
    self._pubsub.emit(event_name, event)
  File "/usr/lib/python3/dist-packages/i3ipc/_private/pubsub.py", line 28, in emit
    s['handler'](self.conn, data)
  File "/home/christian/Bin/inactiveOpacityExceptionCorrected.py", line 33, in on_window_focus
    if workspace.num == prev_workspace and focused_workspace.name != prev_focused_workspace:
                                                                     ^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'prev_focused_workspace' where it is not associated with a value
cannot access local variable 'prev_focused_workspace' where it is not associated with a value
Traceback (most recent call last):
  File "/home/christian/Bin/inactiveOpacityExceptionCorrected.py", line 90, in <module>
    ipc.main()
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 514, in main
    raise loop_exception
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 497, in main
    while not self._event_socket_poll():
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 477, in _event_socket_poll
    raise e
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 474, in _event_socket_poll
    self._pubsub.emit(event_name, event)
  File "/usr/lib/python3/dist-packages/i3ipc/_private/pubsub.py", line 28, in emit
    s['handler'](self.conn, data)
  File "/home/christian/Bin/inactiveOpacityExceptionCorrected.py", line 33, in on_window_focus
    if workspace.num == prev_workspace and focused_workspace.name != prev_focused_workspace:
                                                                     ^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'prev_focused_workspace' where it is not associated with a value
cannot access local variable 'prev_focused_workspace' where it is not associated with a value
Traceback (most recent call last):
  File "/home/christian/Bin/inactiveOpacityExceptionCorrected.py", line 90, in <module>
    ipc.main()
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 514, in main
    raise loop_exception
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 497, in main
    while not self._event_socket_poll():
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 477, in _event_socket_poll
    raise e
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 474, in _event_socket_poll
    self._pubsub.emit(event_name, event)
  File "/usr/lib/python3/dist-packages/i3ipc/_private/pubsub.py", line 28, in emit
    s['handler'](self.conn, data)
  File "/home/christian/Bin/inactiveOpacityExceptionCorrected.py", line 33, in on_window_focus
    if workspace.num == prev_workspace and focused_workspace.name != prev_focused_workspace:
                                                                     ^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'prev_focused_workspace' where it is not associated with a value
Traceback (most recent call last):
  File "/home/christian/Bin/inactiveOpacityException.py", line 110, in <module>
    ipc.main()
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 514, in main
    raise loop_exception
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 497, in main
    while not self._event_socket_poll():
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 430, in _event_socket_poll
    data, msg_type = self._ipc_recv(self._sub_socket)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 129, in _ipc_recv
    data = sock.recv(14)
           ^^^^^^^^^^^^^
  File "/home/christian/Bin/inactiveOpacityException.py", line 108, in <lambda>
    signal.signal(sig, lambda signal, frame: remove_opacity(ipc))
                                             ^^^^^^^^^^^^^^^^^^^
  File "/home/christian/Bin/inactiveOpacityException.py", line 48, in remove_opacity
    for workspace in ipc.get_tree().workspaces():
                     ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 282, in get_tree
    data = self._message(MessageType.GET_TREE, '')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 166, in _message
    raise e
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 163, in _message
    return self._ipc_send(self._cmd_socket, message_type, payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 146, in _ipc_send
    data, msg_type = self._ipc_recv(sock)
                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/i3ipc/connection.py", line 129, in _ipc_recv
    data = sock.recv(14)
           ^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
